from django.contrib import admin
from .models import Tipo_Imovel, Imovel, Cambio, Carroceria, Combustivel, Cor, Itens_veiculo, Carro, Tipo_Motor, Refrigeracao, Estilo, Freio_dianteiro_traseiro, Injecao, Moto, Empresa, Responsabilidades, Requisitos, Beneficio, Emprego, Tipo_servico, Servico

# Register your models here.
admin.site.register(Tipo_Imovel)
admin.site.register(Imovel)
admin.site.register(Cambio)
admin.site.register(Carroceria)
admin.site.register(Combustivel)
admin.site.register(Cor)
admin.site.register(Itens_veiculo)
admin.site.register(Carro)
admin.site.register(Tipo_Motor)
admin.site.register(Refrigeracao)
admin.site.register(Estilo)
admin.site.register(Freio_dianteiro_traseiro)
admin.site.register(Injecao)
admin.site.register(Moto)
admin.site.register(Empresa)
admin.site.register(Responsabilidades)
admin.site.register(Requisitos)
admin.site.register(Beneficio)
admin.site.register(Emprego)
admin.site.register(Tipo_servico)
admin.site.register(Servico)
